### ISSUE TITLE
Documentation Refactoring

### ISSUE THREAD

**Issue by ShreyDixit** [kuffmode/msa#16]
Hi @luisa-hoerauf 

The documentation is old and the current developers are "overfitted" to it. New eyes are appreciated.

Tasks:
- [ ] Go over all the documentation and suggest changes.

All communication can happen on this issue by commenting on your progress and doubts. Once you're done, you can open a pull request which will close this issue.

Regards,
Shrey Dixit

**Comment by kuffmode** [comment]
Man, Github needs reaction gifs. [agreeing gif]
